# Generated by Django 5.1.1 on 2024-09-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disqdb', '0002_alter_pitch_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
